/*
 * Copyright (C) 2017 - present by OpenGamma Inc. and the OpenGamma group of companies
 *
 * Please see distribution for license.
 */
package com.opengamma.strata.product.etd;

import java.io.Serializable;
import java.time.YearMonth;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;

import org.joda.beans.Bean;
import org.joda.beans.BeanDefinition;
import org.joda.beans.ImmutableBean;
import org.joda.beans.ImmutableDefaults;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.PropertyDefinition;
import org.joda.beans.impl.direct.DirectFieldsBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import com.google.common.collect.ImmutableSet;
import com.opengamma.strata.basics.ReferenceData;
import com.opengamma.strata.basics.currency.Currency;
import com.opengamma.strata.product.SecuritizedProduct;
import com.opengamma.strata.product.Security;
import com.opengamma.strata.product.SecurityId;
import com.opengamma.strata.product.SecurityInfo;
import com.opengamma.strata.product.Trade;
import com.opengamma.strata.product.TradeInfo;

/**
 * An instrument representing an exchange traded derivative (ETD) future.
 * <p>
 * A security representing a standardized contact between two parties to buy or sell an asset at a
 * future date for an agreed price.
 */
@BeanDefinition
public final class EtdFutureSecurity
    implements Security, SecuritizedProduct, ImmutableBean, Serializable {

  /**
   * The standard security information.
   * <p>
   * This includes the security identifier.
   */
  @PropertyDefinition(validate = "notNull", overrideGet = true)
  private final SecurityInfo info;
  /**
   * The ID of the contract specification from which this security is derived.
   */
  @PropertyDefinition(validate = "notNull")
  private final EtdContractSpecId contractSpecId;
  /**
   * The expiry month.
   * <p>
   * This is used to describe the instance of the option.
   */
  @PropertyDefinition(validate = "notNull")
  private final YearMonth expiryMonth;
  /**
   * The code representing the actual day of expiry, empty if the ETD is monthly.
   * <p>
   * For example 'W2' for the second weekly contract of the month or '12' for an
   * expiry date of the 12th of the month.
   * <p>
   * If this code is empty then it is a standard monthly contract.
   */
  @PropertyDefinition(validate = "notNull")
  private final String expiryDateCode;

  @ImmutableDefaults
  private static void applyDefaults(Builder builder) {
    builder.expiryDateCode = "";
  }

  //-------------------------------------------------------------------------
  @Override
  public SecurityId getSecurityId() {
    return Security.super.getSecurityId();
  }

  @Override
  public Currency getCurrency() {
    return Security.super.getCurrency();
  }

  @Override
  public ImmutableSet<SecurityId> getUnderlyingIds() {
    return ImmutableSet.of();
  }

  @Override
  public SecuritizedProduct createProduct(ReferenceData refData) {
    return this;
  }

  @Override
  public Trade createTrade(TradeInfo tradeInfo, double quantity, double tradePrice, ReferenceData refData) {
    return EtdFutureTrade.builder()
        .info(tradeInfo)
        .quantity(quantity)
        .price(tradePrice)
        .security(this)
        .build();
  }

  //------------------------- AUTOGENERATED START -------------------------
  ///CLOVER:OFF
  /**
   * The meta-bean for {@code EtdFutureSecurity}.
   * @return the meta-bean, not null
   */
  public static EtdFutureSecurity.Meta meta() {
    return EtdFutureSecurity.Meta.INSTANCE;
  }

  static {
    JodaBeanUtils.registerMetaBean(EtdFutureSecurity.Meta.INSTANCE);
  }

  /**
   * The serialization version id.
   */
  private static final long serialVersionUID = 1L;

  /**
   * Returns a builder used to create an instance of the bean.
   * @return the builder, not null
   */
  public static EtdFutureSecurity.Builder builder() {
    return new EtdFutureSecurity.Builder();
  }

  private EtdFutureSecurity(
      SecurityInfo info,
      EtdContractSpecId contractSpecId,
      YearMonth expiryMonth,
      String expiryDateCode) {
    JodaBeanUtils.notNull(info, "info");
    JodaBeanUtils.notNull(contractSpecId, "contractSpecId");
    JodaBeanUtils.notNull(expiryMonth, "expiryMonth");
    JodaBeanUtils.notNull(expiryDateCode, "expiryDateCode");
    this.info = info;
    this.contractSpecId = contractSpecId;
    this.expiryMonth = expiryMonth;
    this.expiryDateCode = expiryDateCode;
  }

  @Override
  public EtdFutureSecurity.Meta metaBean() {
    return EtdFutureSecurity.Meta.INSTANCE;
  }

  @Override
  public <R> Property<R> property(String propertyName) {
    return metaBean().<R>metaProperty(propertyName).createProperty(this);
  }

  @Override
  public Set<String> propertyNames() {
    return metaBean().metaPropertyMap().keySet();
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the standard security information.
   * <p>
   * This includes the security identifier.
   * @return the value of the property, not null
   */
  @Override
  public SecurityInfo getInfo() {
    return info;
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the ID of the contract specification from which this security is derived.
   * @return the value of the property, not null
   */
  public EtdContractSpecId getContractSpecId() {
    return contractSpecId;
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the expiry month.
   * <p>
   * This is used to describe the instance of the option.
   * @return the value of the property, not null
   */
  public YearMonth getExpiryMonth() {
    return expiryMonth;
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the code representing the actual day of expiry, empty if the ETD is monthly.
   * <p>
   * For example 'W2' for the second weekly contract of the month or '12' for an
   * expiry date of the 12th of the month.
   * <p>
   * If this code is empty then it is a standard monthly contract.
   * @return the value of the property, not null
   */
  public String getExpiryDateCode() {
    return expiryDateCode;
  }

  //-----------------------------------------------------------------------
  /**
   * Returns a builder that allows this bean to be mutated.
   * @return the mutable builder, not null
   */
  public Builder toBuilder() {
    return new Builder(this);
  }

  @Override
  public boolean equals(Object obj) {
    if (obj == this) {
      return true;
    }
    if (obj != null && obj.getClass() == this.getClass()) {
      EtdFutureSecurity other = (EtdFutureSecurity) obj;
      return JodaBeanUtils.equal(info, other.info) &&
          JodaBeanUtils.equal(contractSpecId, other.contractSpecId) &&
          JodaBeanUtils.equal(expiryMonth, other.expiryMonth) &&
          JodaBeanUtils.equal(expiryDateCode, other.expiryDateCode);
    }
    return false;
  }

  @Override
  public int hashCode() {
    int hash = getClass().hashCode();
    hash = hash * 31 + JodaBeanUtils.hashCode(info);
    hash = hash * 31 + JodaBeanUtils.hashCode(contractSpecId);
    hash = hash * 31 + JodaBeanUtils.hashCode(expiryMonth);
    hash = hash * 31 + JodaBeanUtils.hashCode(expiryDateCode);
    return hash;
  }

  @Override
  public String toString() {
    StringBuilder buf = new StringBuilder(160);
    buf.append("EtdFutureSecurity{");
    buf.append("info").append('=').append(info).append(',').append(' ');
    buf.append("contractSpecId").append('=').append(contractSpecId).append(',').append(' ');
    buf.append("expiryMonth").append('=').append(expiryMonth).append(',').append(' ');
    buf.append("expiryDateCode").append('=').append(JodaBeanUtils.toString(expiryDateCode));
    buf.append('}');
    return buf.toString();
  }

  //-----------------------------------------------------------------------
  /**
   * The meta-bean for {@code EtdFutureSecurity}.
   */
  public static final class Meta extends DirectMetaBean {
    /**
     * The singleton instance of the meta-bean.
     */
    static final Meta INSTANCE = new Meta();

    /**
     * The meta-property for the {@code info} property.
     */
    private final MetaProperty<SecurityInfo> info = DirectMetaProperty.ofImmutable(
        this, "info", EtdFutureSecurity.class, SecurityInfo.class);
    /**
     * The meta-property for the {@code contractSpecId} property.
     */
    private final MetaProperty<EtdContractSpecId> contractSpecId = DirectMetaProperty.ofImmutable(
        this, "contractSpecId", EtdFutureSecurity.class, EtdContractSpecId.class);
    /**
     * The meta-property for the {@code expiryMonth} property.
     */
    private final MetaProperty<YearMonth> expiryMonth = DirectMetaProperty.ofImmutable(
        this, "expiryMonth", EtdFutureSecurity.class, YearMonth.class);
    /**
     * The meta-property for the {@code expiryDateCode} property.
     */
    private final MetaProperty<String> expiryDateCode = DirectMetaProperty.ofImmutable(
        this, "expiryDateCode", EtdFutureSecurity.class, String.class);
    /**
     * The meta-properties.
     */
    private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
        this, null,
        "info",
        "contractSpecId",
        "expiryMonth",
        "expiryDateCode");

    /**
     * Restricted constructor.
     */
    private Meta() {
    }

    @Override
    protected MetaProperty<?> metaPropertyGet(String propertyName) {
      switch (propertyName.hashCode()) {
        case 3237038:  // info
          return info;
        case 948987368:  // contractSpecId
          return contractSpecId;
        case 459635981:  // expiryMonth
          return expiryMonth;
        case -1523840754:  // expiryDateCode
          return expiryDateCode;
      }
      return super.metaPropertyGet(propertyName);
    }

    @Override
    public EtdFutureSecurity.Builder builder() {
      return new EtdFutureSecurity.Builder();
    }

    @Override
    public Class<? extends EtdFutureSecurity> beanType() {
      return EtdFutureSecurity.class;
    }

    @Override
    public Map<String, MetaProperty<?>> metaPropertyMap() {
      return metaPropertyMap$;
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-property for the {@code info} property.
     * @return the meta-property, not null
     */
    public MetaProperty<SecurityInfo> info() {
      return info;
    }

    /**
     * The meta-property for the {@code contractSpecId} property.
     * @return the meta-property, not null
     */
    public MetaProperty<EtdContractSpecId> contractSpecId() {
      return contractSpecId;
    }

    /**
     * The meta-property for the {@code expiryMonth} property.
     * @return the meta-property, not null
     */
    public MetaProperty<YearMonth> expiryMonth() {
      return expiryMonth;
    }

    /**
     * The meta-property for the {@code expiryDateCode} property.
     * @return the meta-property, not null
     */
    public MetaProperty<String> expiryDateCode() {
      return expiryDateCode;
    }

    //-----------------------------------------------------------------------
    @Override
    protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
      switch (propertyName.hashCode()) {
        case 3237038:  // info
          return ((EtdFutureSecurity) bean).getInfo();
        case 948987368:  // contractSpecId
          return ((EtdFutureSecurity) bean).getContractSpecId();
        case 459635981:  // expiryMonth
          return ((EtdFutureSecurity) bean).getExpiryMonth();
        case -1523840754:  // expiryDateCode
          return ((EtdFutureSecurity) bean).getExpiryDateCode();
      }
      return super.propertyGet(bean, propertyName, quiet);
    }

    @Override
    protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
      metaProperty(propertyName);
      if (quiet) {
        return;
      }
      throw new UnsupportedOperationException("Property cannot be written: " + propertyName);
    }

  }

  //-----------------------------------------------------------------------
  /**
   * The bean-builder for {@code EtdFutureSecurity}.
   */
  public static final class Builder extends DirectFieldsBeanBuilder<EtdFutureSecurity> {

    private SecurityInfo info;
    private EtdContractSpecId contractSpecId;
    private YearMonth expiryMonth;
    private String expiryDateCode;

    /**
     * Restricted constructor.
     */
    private Builder() {
      applyDefaults(this);
    }

    /**
     * Restricted copy constructor.
     * @param beanToCopy  the bean to copy from, not null
     */
    private Builder(EtdFutureSecurity beanToCopy) {
      this.info = beanToCopy.getInfo();
      this.contractSpecId = beanToCopy.getContractSpecId();
      this.expiryMonth = beanToCopy.getExpiryMonth();
      this.expiryDateCode = beanToCopy.getExpiryDateCode();
    }

    //-----------------------------------------------------------------------
    @Override
    public Object get(String propertyName) {
      switch (propertyName.hashCode()) {
        case 3237038:  // info
          return info;
        case 948987368:  // contractSpecId
          return contractSpecId;
        case 459635981:  // expiryMonth
          return expiryMonth;
        case -1523840754:  // expiryDateCode
          return expiryDateCode;
        default:
          throw new NoSuchElementException("Unknown property: " + propertyName);
      }
    }

    @Override
    public Builder set(String propertyName, Object newValue) {
      switch (propertyName.hashCode()) {
        case 3237038:  // info
          this.info = (SecurityInfo) newValue;
          break;
        case 948987368:  // contractSpecId
          this.contractSpecId = (EtdContractSpecId) newValue;
          break;
        case 459635981:  // expiryMonth
          this.expiryMonth = (YearMonth) newValue;
          break;
        case -1523840754:  // expiryDateCode
          this.expiryDateCode = (String) newValue;
          break;
        default:
          throw new NoSuchElementException("Unknown property: " + propertyName);
      }
      return this;
    }

    @Override
    public Builder set(MetaProperty<?> property, Object value) {
      super.set(property, value);
      return this;
    }

    @Override
    public Builder setString(String propertyName, String value) {
      setString(meta().metaProperty(propertyName), value);
      return this;
    }

    @Override
    public Builder setString(MetaProperty<?> property, String value) {
      super.setString(property, value);
      return this;
    }

    @Override
    public Builder setAll(Map<String, ? extends Object> propertyValueMap) {
      super.setAll(propertyValueMap);
      return this;
    }

    @Override
    public EtdFutureSecurity build() {
      return new EtdFutureSecurity(
          info,
          contractSpecId,
          expiryMonth,
          expiryDateCode);
    }

    //-----------------------------------------------------------------------
    /**
     * Sets the standard security information.
     * <p>
     * This includes the security identifier.
     * @param info  the new value, not null
     * @return this, for chaining, not null
     */
    public Builder info(SecurityInfo info) {
      JodaBeanUtils.notNull(info, "info");
      this.info = info;
      return this;
    }

    /**
     * Sets the ID of the contract specification from which this security is derived.
     * @param contractSpecId  the new value, not null
     * @return this, for chaining, not null
     */
    public Builder contractSpecId(EtdContractSpecId contractSpecId) {
      JodaBeanUtils.notNull(contractSpecId, "contractSpecId");
      this.contractSpecId = contractSpecId;
      return this;
    }

    /**
     * Sets the expiry month.
     * <p>
     * This is used to describe the instance of the option.
     * @param expiryMonth  the new value, not null
     * @return this, for chaining, not null
     */
    public Builder expiryMonth(YearMonth expiryMonth) {
      JodaBeanUtils.notNull(expiryMonth, "expiryMonth");
      this.expiryMonth = expiryMonth;
      return this;
    }

    /**
     * Sets the code representing the actual day of expiry, empty if the ETD is monthly.
     * <p>
     * For example 'W2' for the second weekly contract of the month or '12' for an
     * expiry date of the 12th of the month.
     * <p>
     * If this code is empty then it is a standard monthly contract.
     * @param expiryDateCode  the new value, not null
     * @return this, for chaining, not null
     */
    public Builder expiryDateCode(String expiryDateCode) {
      JodaBeanUtils.notNull(expiryDateCode, "expiryDateCode");
      this.expiryDateCode = expiryDateCode;
      return this;
    }

    //-----------------------------------------------------------------------
    @Override
    public String toString() {
      StringBuilder buf = new StringBuilder(160);
      buf.append("EtdFutureSecurity.Builder{");
      buf.append("info").append('=').append(JodaBeanUtils.toString(info)).append(',').append(' ');
      buf.append("contractSpecId").append('=').append(JodaBeanUtils.toString(contractSpecId)).append(',').append(' ');
      buf.append("expiryMonth").append('=').append(JodaBeanUtils.toString(expiryMonth)).append(',').append(' ');
      buf.append("expiryDateCode").append('=').append(JodaBeanUtils.toString(expiryDateCode));
      buf.append('}');
      return buf.toString();
    }

  }

  ///CLOVER:ON
  //-------------------------- AUTOGENERATED END --------------------------
}
